// ROUTER PRINCIPAL - Agrupa todas las rutas del sistema
const express = require('express')
const router = express.Router()

// Importar rutas por modulo
const authRoutes = require('./auth.routes')
const userRoutes = require('./user.routes')
const clientRoutes = require('./client.routes')
const petRoutes = require('./pet.routes')
const veterinarianRoutes = require('./veterinarian.routes')
const serviceRoutes = require('./service.routes')
const appointmentRoutes = require('./appointment.routes')
const vaccineRoutes = require('./vaccine.routes')
const nutritionRoutes = require('./nutrition.routes')
const notificationRoutes = require('./notification.routes')
const adminRoutes = require('./admin.routes')
const smsRoutes = require('./sms.routes')

// Montar rutas con sus prefijos
router.use('/auth', authRoutes)                 // /api/auth/...
router.use('/usuarios', userRoutes)             // /api/usuarios/...
router.use('/clientes', clientRoutes)           // /api/clientes/...
router.use('/mascotas', petRoutes)              // /api/mascotas/...
router.use('/veterinarios', veterinarianRoutes) // /api/veterinarios/...
router.use('/servicios', serviceRoutes)         // /api/servicios/...
router.use('/citas', appointmentRoutes)         // /api/citas/...
router.use('/vacunas', vaccineRoutes)           // /api/vacunas/...
router.use('/alimentacion', nutritionRoutes)    // /api/alimentacion/...
router.use('/notificaciones', notificationRoutes) // /api/notificaciones/...
router.use('/administradores', adminRoutes)     // /api/administradores/...
router.use('/sms', smsRoutes)                   // /api/sms/...

module.exports = router